"""add endpoint_url to model_configs

Revision ID: 6b02d0009cd7
Revises: 1572b430419e
Create Date: 2026-08-11 13:52:48.634146+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b02d0009cd7'
down_revision: Union[str, None] = '1572b430419e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_column('endpoint_url')

    # ### end Alembic commands ###
